#!/bin/bash
cd "`dirname \"$0\"`"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#test for network connection due to cron
while ! wget -q --tries=3 --timeout=20 http://google.com -O- >/dev/null
do
	sleep 3
done

while true; do
	nodejs app.js > console.log 2>&1
	OUT=$?
	if [ $OUT -ne 0 ];then
		crashfile="crash_`date +%s`.log"
		tail -n 50 console.log >> "$crashfile"
		echo "Server exited with code $OUT" | tee -a "$crashfile"
		sleep 15
	else
		break
	fi

done
