#!/bin/bash
cd "`dirname \"$0\"`"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

while true; do
	/usr/bin/node app.js && echo normal shutdown || (echo ABNORMAL TERMINATION >&2;echo "";sleep 3)
	sleep 0.3
done
